# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Cerebri-Watson-Connector
  description: Call Watson services via a Restful interface, without the compliations of watson setup and configuration
  version: "0.01"
# the domain of the service
host: flask-watson
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /piroute:
    post:
      summary: Facebook -> Personality Insights
      description: |
        piroute endpoint takes facebook credentials from a user authorizing an app, and returns personality insights (IBM) about their posts.
      parameters:
        - name: oauth_token
          in: query
          description: Authentication Token from Facebook
          required: true
          type: string
          format: char
        - name: user_id
          in: query
          description: Facebook Id of user
          required: true
          type: string
          format: int
      tags:
        - Watson
      responses:
        200:
          description: Personality
          schema:
            $ref: '#/definitions/PIVector'
        400:
          description: Error
          schema:
            $ref: '#/definitions/ErrorVector'
 
 
  
 
definitions:
  PIVector:
    type: object
    properties:
      id:
        type: string
        description: Id of call
      processed_lang:
        type: string
        description: Language Code
      source:
        type: string
        description: Display name of product.
      tree:
        type: string
        description: PI data 
      word_count:
        type: string
        description: Number of words passed to the call
      word_count_message:
        type: string
        description: Information about the word count. 
      warnings:
        type: string
        description: Array of warnings that can occur. 
  ErrorVector:
    type: object
    properties:
      message:
        type: string
        description: Json String with error information. 